---  
- name: Deploy Digital Ocean Droplet 
  digital_ocean:
      api_token: "{{ do_api_key }}" 
      state: present
      command: droplet
      name: "{{ item }}" 
      size_id: "{{ droplet_size }}"
      region_id: "{{ do_region }}"
      image_id: "{{ droplet_image_id }}"
      ssh_key_ids: "{{ do_ssh_key_id }}"
  with_items: "{{ droplet_name }}"
  register: do_response

- debug:
    msg: "Droplet ID({{ item.droplet.id }}) - IP({{ item.droplet.ip_address }})"
  with_items: "{{ do_response.results }}"
  loop_control:
    label: "{{ item.droplet.id }}"

- name: Creating host group "ddo_group"
  add_host:
    name: "{{ item.droplet.ip_address }}"
    groups: ddo_group
  with_items: "{{ do_response.results }}"
  loop_control:
    label: "{{ item.droplet.id }}"

- name: Setting droplet_id Fact
  set_fact:
    droplet_id: "{{ item.droplet.id }}"
  with_items: "{{ do_response.results }}"
