---
- name: Deploy Digital Ocean Droplet 
  digital_ocean:
      api_token: "{{ do_api_key }}" 
      state: present
      command: droplet
      name: "{{ droplet_name }}" 
      size_id: "{{ droplet_size }}"
      region_id: "{{ do_region }}"
      image_id: "{{ droplet_image_id }}"
      ssh_key_ids: "{{ do_ssh_key_id }}"
  register: do_response

- debug: msg="Droplet ID {{ do_response.droplet.id }} \n Droplet IP {{ do_response.droplet.ip_address }}."

- name: Create Ansible Managed Tag
  digital_ocean_tag:
      api_token: "{{ do_api_key }}"
      name: "{{ do_tag_name }}"
      state: present

- name: Tagging Droplet
  digital_ocean_tag:
      api_token: "{{ do_api_key }}"
      name: "{{ do_tag_name }}"
      resource_id: "{{ do_response.droplet.id }}"
      state: present
