---
- name: Create Ansible Managed Tag
  digital_ocean_tag:
      api_token: "{{ do_api_key }}"
      name: "{{ do_tag_name }}"
      state: present

- name: Tagging Droplet
  digital_ocean_tag:
      api_token: "{{ do_api_key }}"
      name: "{{ do_tag_name }}"
      resource_id: "{{ item.droplet.id }}"
      state: present
  with_items: "{{ do_response.results }}"
  loop_control:
    label: "{{ item.droplet.id }}"